name: Go
on: [ push, pull_request ]
jobs:
  test:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.4'
      - name: Run tests and generate coverage report
        run: go test -coverprofile cover.out -covermode atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./cover.out
          fail_ci_if_error: true

  vet:
    name: go vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.4'
      - uses: actions/checkout@v3
      - name: go vet
        run: go vet ./...

  gocyclo:
    name: gocyclo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.4'
      - name: Install gocyclo
        run: go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
      - uses: actions/checkout@v3
      - name: gocyclo
        run: gocyclo -over 14 .

  staticcheck:
    name: staticcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.4'
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - uses: actions/checkout@v3
      - name: staticcheck
        run: staticcheck ./...
